### ISSUE TITLE
有没有成功的成功的请扣字1

### ISSUE THREAD

**Issue by ghost** [Upsetin/noss-mint-script#13]
有没有成功的成功的请扣字1

**Comment by xspoco** [comment]
没打到
![image](https://github.com/Upsetin/noss-mint-script/assets/19290455/2a64c2d9-2a3f-44cd-9430-898b39f14b26)
现在出现一堆这个不知道是不是报错

**Comment by MinLouLou** [comment]
你这个不是报错，是打印了网页信息。

**Comment by xrsphp** [comment]
24小时了 两台服务器 都没挖到

**Comment by LgdSoft** [comment]
我也是出现了这个，但是好像并没有挖到

**Comment by ghost** [comment]
> 我也出现了这个，但是想要并没有挖到

你测试了多久

**Comment by LgdSoft** [comment]
> > 我也出现了这个，但是想要并没有挖到
> 
> 你测试了多长时间

一晚上了

**Comment by xrsphp** [comment]
![git22](https://github.com/Upsetin/noss-mint-script/assets/25739959/c0fe0ae8-b7e8-467e-808b-33de09fe16e9)
打印出来的网页内容是这样的 感觉再挂多久也没意义

**Comment by LgdSoft** [comment]
我的也是这样，不知道有没有人成功

**Comment by ghost** [comment]
> > > 我也出现了这个，但是想要并没有挖到
> > 
> > 
> > 你测试了多长时间
> 
> 一晚上了

一晚上都没有成功吗

**Comment by LgdSoft** [comment]
> > > > 我也出现了这个，但是想要并没有挖到
> > > 
> > > 
> > > 你测试了多长时间
> > 
> > 
> > 一晚上了
> 
> 一晚上都没有成功吗

反正网站查询那里还是0

**Comment by ghost** [comment]
> > > > > 我也出现了这个，但是想要并没有挖到
> > > > 
> > > > 
> > > > 你测试了多长时间
> > > 
> > > 
> > > 一晚上了
> > 
> > 
> > 一晚上都没有成功吗
> 
> 目前网站查询那里还是0
老兄加个微信吧 tytsxai

**Comment by LgdSoft** [comment]
+了

**Comment by 728443778** [comment]
用网页挖吧，有个反作弊验证的算法，纵然逆向出来了，但官方随时都会更换算法或者规则

**Comment by haloowhite** [comment]
这是网页上了cloudflare，新版本已经解决了这个问题，记得运行之前install最新的依赖

**Comment by LgdSoft** [comment]
> 这是网页上了cloudflare，新版本已经解决了这个问题，记得运行之前install最新的依赖

但是又挖了好久，还是一个都没呢

**Comment by 2wong** [comment]
应该是算法错了，而且提交的body貌似格式有些问题

**Comment by champ75** [comment]
兄弟，还有个提交request的时候新增了一个header. 群里看到的。

**Comment by champ75** [comment]
![Screenshot_20240107_014323](https://github.com/Upsetin/noss-mint-script/assets/155841286/f211f711-bc88-477c-a597-62c5d5bddea4)
![Screenshot_20240107_014347](https://github.com/Upsetin/noss-mint-script/assets/155841286/3c1bcbac-7637-4af5-901e-bf123d205dd3)
